DROP DATABASE IF EXISTS tracker;
CREATE DATABASE tracker;
USE tracker;
CREATE TABLE department (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	department_name VARCHAR(40) NOT NULL
    );

CREATE TABLE role (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	title VARCHAR(30) NOT NULL,
	salary DECIMAL(10, 2) NOT NULL,
	department_id INT NOT NULL
	);

CREATE TABLE employee (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INT NOT NULL,
  manager_id INT
 );



